# Generated by Django 5.1.7 on 2025-09-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_login", models.CharField(max_length=150, unique=True)),
                ("user_password", models.CharField(max_length=255)),
                ("user_compte_id", models.IntegerField(unique=True)),
                ("user_mail", models.CharField(max_length=255)),
                ("user_date_new", models.DateTimeField(auto_now_add=True)),
                ("user_date_login", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
