# Generated by Django 5.2.6 on 2025-10-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("designation_p", models.CharField(max_length=255)),
                ("type_p", models.CharField(max_length=100)),
                ("prix_ht", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_p", models.IntegerField(default=0)),
                ("date_in", models.DateField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="produits/"),
                ),
            ],
        ),
    ]
